"""
HTTP client for Twitch API requests.

Handles HTTP session management, request retries, and connection quality settings.
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
import os
import tempfile
import time
from collections import abc
from contextlib import asynccontextmanager
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import TYPE_CHECKING

import aiohttp
from yarl import URL

from src.config import COOKIES_PATH
from src.exceptions import ExitRequest, RequestInvalid
from src.i18n import _
from src.utils import ExponentialBackoff


if TYPE_CHECKING:
    from src.config import ClientInfo
    from src.config.settings import Settings
    from src.core.client import Twitch
    from src.web.gui_manager import WebGUIManager


logger = logging.getLogger("TwitchDrops")


# Naming and lifetime of the temporary file CookieJarStore writes beside the jar.
# Mirrors src/utils/json_utils.py on purpose: the same dotted-prefix convention
# keeps leftovers out of any glob that scans the data directory, and each scheme
# only ever collects temps belonging to its own target.
_TEMP_SUFFIX = ".tmp"
# A jar write takes milliseconds, so a temp file older than this belongs to a
# process that died before its rename - never to a write currently in flight.
_STALE_TEMP_AGE = 3600.0
# The mode the live jar is guaranteed to have. It holds the Twitch auth-token,
# so other users on the host must not be able to read it.
_PRIVATE_FILE_MODE = 0o600


class CookieJarStore:
    """
    Crash-atomic persistence for an :class:`aiohttp.CookieJar`.

    ``aiohttp.CookieJar.save()`` is ``path.open("wb")`` plus ``pickle.dump``, so
    it truncates the jar BEFORE the new bytes land. A SIGKILL, a power cut or a
    full disk in between leaves a truncated ``cookies.jar``; the next start
    cannot unpickle it, comes up logged out, and a logged-out miner mines
    nothing. That is the same durability class ``json_save`` closed for
    settings.json, reached from the credential side instead.

    So every write goes into a temporary file in the jar's OWN directory (same
    filesystem, so the rename cannot cross devices), is flushed and ``fsync``ed,
    and only then ``os.replace``d onto the jar. A reader therefore always sees
    either the complete previous jar or the complete new one, never a half of
    either, and a failure anywhere before the replace leaves the previous jar
    untouched and takes the temporary file back out of the directory.

    The jar carries a live Twitch auth-token, so it must stay unreadable to other
    users on the host. ``tempfile.mkstemp`` creates the temporary file 0o600
    whatever the umask, ``CookieJar.save()`` reopening that existing path with
    ``"wb"`` truncates it without touching its mode, and ``os.replace`` carries
    0o600 onto the target - which also tightens a jar that pre-dates this class
    and was left 0o644 by ``open()``. This replaces the explicit ``chmod`` the
    two call sites used to run afterwards, and closes the window that chmod left
    open, in which the token sat in a world-readable file.

    Deliberately NOT routed through ``json_save``: the payload is aiohttp's
    pickle format, not JSON, and the format stays aiohttp's to own. Like
    ``json_save`` this does not fsync the directory either, so it shares the same
    accepted residual - a power cut can lose the rename itself, which leaves the
    previous complete jar in place.
    """

    def __init__(self, path: Path):
        """
        Parameters
        ----------
        path : Path
            The jar file to read and write, normally ``COOKIES_PATH``.
        """
        self._path = path

    @property
    def path(self) -> Path:
        """The jar file this store reads and writes."""
        return self._path

    def load(self, jar: aiohttp.CookieJar) -> bool:
        """
        Restore ``jar`` from disk, returning whether anything was actually read.

        A jar that cannot be read is not fatal and never was:
        ``CookieJar.load()`` assigns ``self._cookies`` only after ``pickle.load``
        returns, so a truncated or unpicklable file leaves the jar exactly as it
        came in - empty - and the miner degrades to logged out and asks for a
        fresh device-code login. What it used to do is that silently, which from
        the outside is indistinguishable from Twitch having revoked the session,
        so the event is now reported at WARNING with the path and the error on it.

        Deliberately NOT quarantined the way ``json_load`` preserves a corrupt
        settings.json: a settings file holds choices that cannot be derived
        again, while the jar holds a credential that is regenerated by logging
        in. Keeping unreadable copies of an auth-token around would buy nothing
        and add exposure.
        """
        # Collect the previous run's leftovers here rather than only after a
        # successful write, the way json_save does: the jar is written on login
        # and on clean shutdown, so a container that is always SIGKILLed reaches
        # a successful save rarely - but it passes through this method on every
        # start, which makes startup the reliable collection point.
        self._sweep_stale_temps()
        path = self._path
        if not path.exists():
            return False
        try:
            # ``CookieJar.load()`` unpickles, which executes whatever the file
            # says. Accepted, and unchanged by this class: the jar is written by
            # this process into its own DATA_DIR at 0o600 and is never accepted
            # from anywhere else, so anyone able to plant a payload in it can
            # already run code as this user. Switching the format is aiohttp's
            # call, not ours - see the class docstring on not owning it.
            jar.load(path)
        except Exception as exc:
            jar.clear()
            logger.warning(
                f"Could not read the cookie jar at {path} ({type(exc).__name__}: {exc}). "
                "Continuing with an empty jar, so a new Twitch login will be required."
            )
            return False
        return True

    def save(self, jar: aiohttp.CookieJar) -> None:
        """
        Write ``jar`` to disk atomically, at ``_PRIVATE_FILE_MODE``.

        Raises whatever the write raises (a full disk, a read-only data
        directory) rather than deciding for its callers, exactly as the direct
        ``CookieJar.save()`` calls this replaces did. Both callers report it and
        carry on, which only became the right answer once the write was atomic:
        a failure now leaves the previous jar whole, so the cost is at most a
        re-login at the next start, and neither losing the session nor stopping
        the miner.

        Note the one behaviour this does change: ``os.replace`` needs write
        permission on the *directory*, not just on the jar, so a data directory
        that is read-only to the process while ``cookies.jar`` itself is
        writable used to save fine and now raises. That is the same accepted
        residual ``json_save`` carries, and correctly so - such a write could
        never have been made durable anyway.
        """
        path = self._path
        # A dotted prefix keeps a leftover temp file (kill -9 between the write
        # and the replace) out of the way of any glob that scans the data dir.
        fd, temp_name = tempfile.mkstemp(
            dir=path.parent, prefix=f".{path.name}.", suffix=_TEMP_SUFFIX
        )
        temp_path = Path(temp_name)
        # CookieJar.save() wants a path of its own to open, and opening an
        # EXISTING file with "wb" truncates it without changing its mode, so the
        # token never lands in a file readable by anyone else - not even for the
        # length of one write. mkstemp already created it 0o600 whatever the
        # umask; the chmod restates that as something this class enforces rather
        # than inherits from a stdlib detail, and is best-effort precisely
        # because mkstemp has already done the load-bearing part.
        os.close(fd)
        with contextlib.suppress(OSError):
            os.chmod(temp_path, _PRIVATE_FILE_MODE)
        try:
            jar.save(temp_path)
            # Closing its file flushed CookieJar.save()'s own buffer, but only as
            # far as the page cache - nothing has reached the disk yet. Force it
            # out before the rename, or a power cut can leave the target renamed
            # onto an empty inode: precisely the truncation this exists to
            # prevent, just moved one step later. Reopened "rb+" rather than "wb"
            # because "wb" would truncate the bytes we are trying to persist.
            with open(temp_path, "rb+") as file:
                os.fsync(file.fileno())
            os.replace(temp_path, path)
        except BaseException:
            # Pickling error, disk full, permission error - the previous jar is
            # still whole, so just take the temp file back out of the directory.
            with contextlib.suppress(OSError):
                temp_path.unlink()
            raise
        # Only after the write succeeded: a sweep must never be what makes one
        # fail, and there is nothing to collect until this one is safely landed.
        self._sweep_stale_temps()

    def _sweep_stale_temps(self) -> None:
        """
        Delete this jar's own abandoned temp files.

        Only temps belonging to THIS target are considered, and only ones older
        than ``_STALE_TEMP_AGE``, so a write running concurrently in another
        process - its temp file is seconds old - is never robbed of the file it
        is about to rename. Every failure is ignored: reaping garbage must never
        turn a successful write, or a successful start, into a failed one.
        """
        path = self._path
        cutoff = time.time() - _STALE_TEMP_AGE
        with contextlib.suppress(OSError):
            for temp in path.parent.glob(f".{path.name}.*{_TEMP_SUFFIX}"):
                with contextlib.suppress(OSError):
                    if temp.stat().st_mtime < cutoff:
                        temp.unlink()


class HTTPClient:
    """
    Manages HTTP session and handles request retries with exponential backoff.

    This client provides:
    - Session management with cookie persistence
    - Automatic request retries on connection errors
    - Connection quality-based timeout configuration
    - Proxy support
    """

    def __init__(
        self,
        settings: Settings,
        gui: WebGUIManager,
        twitch: Twitch,
        client_type: ClientInfo,
    ):
        """
        Initialize the HTTP client.

        Parameters
        ----------
        settings : Settings
            Application settings for connection quality and proxy configuration
        gui : WebGUIManager
            GUI manager for user notifications
        twitch : Twitch
            Twitch client for state checking
        client_type : ClientInfo
            Client type information (User-Agent, Client-ID, etc.)
        """
        self.settings = settings
        self.gui = gui
        self._twitch = twitch
        self._client_type = client_type
        self._session: aiohttp.ClientSession | None = None
        self._cookie_store = CookieJarStore(COOKIES_PATH)

    async def get_session(self) -> aiohttp.ClientSession:
        """
        Get or create the HTTP session.

        Returns
        -------
        aiohttp.ClientSession
            The active HTTP session

        Raises
        ------
        RuntimeError
            If the session is closed
        """
        if (session := self._session) is not None:
            if session.closed:
                raise RuntimeError("Session is closed")
            return session

        # Load cookies. An unreadable jar is not fatal: the store clears it,
        # logs why at WARNING, and the miner logs in again.
        cookie_jar = aiohttp.CookieJar()
        self._cookie_store.load(cookie_jar)

        # Create timeouts based on connection quality
        connection_quality = self.settings.connection_quality
        if connection_quality < 1:
            connection_quality = self.settings.connection_quality = 1
        elif connection_quality > 6:
            connection_quality = self.settings.connection_quality = 6

        timeout = aiohttp.ClientTimeout(
            sock_connect=5 * connection_quality,
            total=10 * connection_quality,
        )

        # Create session with connection pooling
        connector = aiohttp.TCPConnector(limit=50)
        self._session = aiohttp.ClientSession(
            timeout=timeout,
            connector=connector,
            cookie_jar=cookie_jar,
            headers={"User-Agent": self._client_type.USER_AGENT},
        )
        return self._session

    @asynccontextmanager
    async def request(
        self,
        method: str,
        url: URL | str,
        *,
        invalidate_after: datetime | None = None,
        **kwargs,
    ) -> abc.AsyncIterator[aiohttp.ClientResponse]:
        """
        Make an HTTP request with automatic retries.

        Parameters
        ----------
        method : str
            HTTP method (GET, POST, etc.)
        url : URL | str
            Request URL
        invalidate_after : datetime | None, optional
            Datetime after which the request should not be retried
        **kwargs
            Additional arguments passed to aiohttp.ClientSession.request

        Yields
        ------
        aiohttp.ClientResponse
            The HTTP response

        Raises
        ------
        ExitRequest
            If the application is closing
        RequestInvalid
            If the request expires during retry loop
        aiohttp.ClientConnectorCertificateError
            If SSL verification fails
        """
        session = await self.get_session()
        method = method.upper()

        if self.settings.proxy and "proxy" not in kwargs:
            kwargs["proxy"] = self.settings.proxy

        logger.debug(f"Request: ({method=}, {url=}, {kwargs=})")
        session_timeout = timedelta(seconds=session.timeout.total or 0)
        backoff = ExponentialBackoff(maximum=3 * 60)

        for delay in backoff:
            from src.config import State

            if self._twitch._state == State.EXIT:
                raise ExitRequest()
            elif (
                invalidate_after is not None
                # Account for expiration landing during the request
                and datetime.now(timezone.utc) >= (invalidate_after - session_timeout)
            ):
                raise RequestInvalid()

            try:
                response: aiohttp.ClientResponse | None = None
                response = await session.request(method, url, **kwargs)
                assert response is not None
                logger.debug(f"Response: {response.status}: {response}")

                if response.status < 500:
                    # Pre-read the response to avoid getting errors outside the context manager
                    raw_response = await response.read()  # noqa: F841
                    yield response
                    return

                self.gui.print(_.t["error"]["site_down"].format(seconds=round(delay)))
            except aiohttp.ClientConnectorCertificateError:
                # SSL verification failures should not be retried
                raise
            except (
                aiohttp.ClientConnectionError,
                asyncio.TimeoutError,
                aiohttp.ClientPayloadError,
            ):
                # Connection problems, retry with backoff
                if backoff.steps > 1:
                    # Don't show quick retries to the user
                    self.gui.print(_.t["error"]["no_connection"].format(seconds=round(delay)))
            finally:
                if response is not None:
                    response.release()

            # Wait for the backoff delay
            await asyncio.sleep(delay)

    async def close(self) -> None:
        """
        Close the HTTP session and save cookies.

        This should be called during application shutdown.
        """
        if self._session is not None:
            cookie_jar = self._session.cookie_jar
            assert isinstance(cookie_jar, aiohttp.CookieJar)

            # Clear empty cookie entries before saving
            # NOTE: Unfortunately, aiohttp provides no easy way of clearing empty cookies,
            # so we need to access the private '_cookies' attribute
            for cookie_key, cookie in list(cookie_jar._cookies.items()):
                if not cookie:
                    del cookie_jar._cookies[cookie_key]

            # Atomic, and 0o600 by construction - cookies.jar contains the
            # Twitch auth-token, and a shutdown interrupted mid-write must not
            # be able to cost the session. See CookieJarStore.
            try:
                self._cookie_store.save(cookie_jar)
            except Exception:
                # Letting this escape aborts the rest of Twitch.close() - the
                # session below is never closed, and the drop/channel/auth
                # state after it is never cleared - over a file whose previous
                # contents the atomic write has already left intact. So the
                # failure is reported and the shutdown finishes.
                logger.error(
                    f"Could not save the cookie jar to {self._cookie_store.path}. "
                    "The previous jar is untouched, so a stored session still restores, "
                    "but anything this run changed about it is lost.",
                    exc_info=True,
                )
            await self._session.close()
            self._session = None
